@API_URL=http://127.0.0.1:8000


GET {{API_URL}}/api/admin/categories HTTP/1.1
Content-Type: application/json
accept: application/json


### [ Create Category ]
POST {{API_URL}}/api/admin/category/store HTTP/1.1
Content-Type: application/json
accept: application/json

{
"cat_name":" Technology"

}


### [ Update Category ]
POST {{API_URL}}/api/admin/category/update HTTP/1.1
Content-Type: application/json
accept: application/json

{
"id":3,
"cat_name":" Technology"

}


### [ Delete Category ]

DELETE {{API_URL}}/api/admin/category/destroy/2 HTTP/1.1
Content-Type: application/json
accept: application/json
