@API_URL=http://127.0.0.1:8000
@TOKEN=Bearer 39|vlIvjTsqNTwVR6Q402tekUY8CaYhtoP3yYvPNXfy

### [ All post ]
GET {{API_URL}}/api/admin/posts HTTP/1.1
Content-Type: application/json
accept: application/json
Authorization:{{TOKEN}}


### [ Create post ]
POST {{API_URL}}/api/admin/post/store HTTP/1.1
Content-Type: application/json
accept: application/json
Authorization:{{TOKEN}}

{
"title":"this is check title",
"description":"this is blog content",
"cat_id":"4,6,"

}

### [ Delete Post ]

DELETE {{API_URL}}/api/admin/post/destroy/6 HTTP/1.1
Content-Type: application/json
accept: application/json
Authorization:{{TOKEN}}
